### ISSUE TITLE
Power Plug space for case-para-toradex-iris

### ISSUE THREAD

**Issue by andrecurvello** [Patola/3dmodels#1]
Hi there!
In the "case-para-toradex-iris" 3D model, it has a problem about the space for the Iris Power Plug.
Using the default connector supplied with the Iris Baseboard, the present "window space" is not enough for a properly connection. 
The plug can be connected, the board can be turned on inside the case, but even a small force can unplug the connector. 
So, could you open the "window space" for the power plug connection?
Thanks,
Andre Curvello.

**Comment by Patola** [comment]
Sure, working on it! Thanks for the bug report!

**Comment by Patola** [comment]
Enlarged the power connector hole. Will send you the fixed 3d print.
